arch:
  - arm64
os:
  - linux
services:
  - docker
before_install:
  - docker login -u "$DOCKER_USERNAME" -p $DOCKER_PASSWORD
script: 
  - export pwd=$PWD && echo $PWD
  - export BUILD_TAG=2.0.3
  - cd build
  - docker build . -f Dockerfile.Slim -t toyangdon/nacos-server:$BUILD_TAG
  - docker push toyangdon/nacos-server:$BUILD_TAG
